network:
  net:
    attention:
      multi_query: false
      in_mv_channels: null
      out_mv_channels: null
      in_s_channels: null
      out_s_channels: null
      num_heads: 8
      additional_qk_mv_channels: 0
      additional_qk_s_channels: 0
      pos_encoding: false
      pos_enc_base: 4096
      output_init: default
      checkpoint: true
      increase_hidden_channels: 2
      dropout_prob: null
    mlp:
      mv_channels: null
      s_channels: null
      activation: gelu
      dropout_prob: null
    _target_: gatr.nets.GATr
    in_mv_channels: 1
    out_mv_channels: 1
    hidden_mv_channels: 64
    in_s_channels: 4
    out_s_channels: 1
    hidden_s_channels: 32
    num_blocks: 8
    reinsert_mv_channels: null
    reinsert_s_channels: null
    dropout_prob: null
  _target_: experiments.wrappers.AmplitudeGATrWrapper
  reinsert_type_token: false
run_name: gggh_uw_gatr
data:
  dataset:
  - gggh_test
  data_path: data/
  kfac: false
  particles_prepd_mean: null
  particles_prepd_std: 117.0358847144214
  prepd_mean: -14.650970635600725
  prepd_std: 1.5324145525457673
run_dir: ${base_dir}/models/gggh_gatr
