model:
  net:
    attention:
      multi_query: false
      in_mv_channels: null
      out_mv_channels: null
      in_s_channels: null
      out_s_channels: null
      num_heads: 8
      additional_qk_mv_channels: 0
      additional_qk_s_channels: 0
      pos_encoding: false
      pos_enc_base: 4096
      output_init: default
      checkpoint: true
      increase_hidden_channels: 2
      dropout_prob: null
    mlp:
      mv_channels: null
      s_channels: null
      activation: gelu
      dropout_prob: null
    _target_: gatr.nets.GATr
    in_mv_channels: 1
    out_mv_channels: 1
    hidden_mv_channels: 64
    in_s_channels: 4
    out_s_channels: 1
    hidden_s_channels: 32
    num_blocks: 8
    reinsert_mv_channels: null
    reinsert_s_channels: null
    dropout_prob: null
  _target_: experiments.wrappers.AmplitudeGATrWrapper
  reinsert_type_token: false
exp_name: amp
exp_type: amplitudes
run_name: gg_tth_loop_gatr
enable_flash_sdp: false
enable_math_sdp: true
enable_mem_efficient_sdp: false
evaluation:
  batchsize: 1024
defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  run:
    dir: .
  output_subdir: null
base_dir: ./
data:
  dataset:
  - gg_tth_loop_test
  data_path: data/
  kfac: true
  particles_prepd_mean: null
  particles_prepd_std: 1.3009485919290988
  prepd_mean: null
  prepd_std: null
run_idx: 0
run_dir: ./models/gg_tth_loop_gatr
